"""Initial migration

Revision ID: 14627bb28b54
Revises: 241fbfdf0556
Create Date: 2025-03-30 15:58:53.914610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_users_db_sqlalchemy import GUID


# revision identifiers, used by Alembic.
revision: str = '14627bb28b54'
down_revision: Union[str, None] = '241fbfdf0556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('id', GUID(), nullable=True))
    op.add_column('links', sa.Column('user_id', GUID(), nullable=True))
    op.alter_column('links', 'short_code',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.drop_index('ix_links_short_code', table_name='links')
    op.create_index(
        op.f('ix_links_short_code'),
        'links',
        ['short_code'],
        unique=True)
    op.create_foreign_key(None, 'links', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'links', type_='foreignkey')
    op.drop_index(op.f('ix_links_short_code'), table_name='links')
    op.create_index(
        'ix_links_short_code',
        'links',
        ['short_code'],
        unique=False)
    op.alter_column('links', 'short_code',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.drop_column('links', 'user_id')
    op.drop_column('links', 'id')
    # ### end Alembic commands ###
