"""Initial migration

Revision ID: 918ff27c4f82
Revises: 14627bb28b54
Create Date: 2025-03-30 18:59:49.610474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '918ff27c4f82'
down_revision: Union[str, None] = '14627bb28b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('links', 'id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('links', 'short_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('links', 'short_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('links', 'id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
